Elevator:
  BlockType: IRON_BLOCK
  BlockDistance: 50
  EnableParticle: true
  ParticleType: WITCH
  ParticleCount: 20
  UsageSound: entity.enderman.teleport
  ActivateSound: entity.player.levelup
  AllowUnsafe: false
Teleporter:
  BlockType: SEA_LANTERN
  EnableParticle: true
  UsageSound: entity.enderman.teleport
  WarmupTime: 3
  AllowUnsafe: false
Hooks:
  GriefPrevention: true
  GriefDefender: true
  WorldGuard: true
Cooldown:
  EnableCooldown: false
  Time: 30
  Locale: '<red>Elevator is on cooldown. Please wait for another %time% seconds!'
ElevatorLocale:
  ElevatorUp: '<green>Going up'
  ElevatorDown: '<green>Going down'
  ElevatorDanger: '<red>Danger! You cannot use the elevator to this location. You might die!'
  ElevatorActivated: '<green>The elevator is active'
TeleporterLocale:
  Danger: '<red>Danger! The location is not safe!'
  LinkSelf: '<red>You can''t link to the same teleporter.'
  Cancelled: '<red>Teleportation cancelled!'
  Initialized: '<aqua>Teleportation initialized'
  Warmup: '<aqua>Please wait <blue>%time% <aqua>seconds while the teleporter initializes! Don''t move!'
  UnvalidBlock: '<red>Not a valid teleporter block detected!'
  Exist: '<red>This teleporter already exists!'
  Unexist: '<red>One or more teleporters do not exist. Check for spelling errors.'
  Added: '<yellow>Teleporter has been added as <gold>%tpname%'
  LinkExist: '<red>One or more teleporters are already linked.'
  NoOwner: '<red>You are not allowed to link those teleporters.'
  Linked: '<yellow>You have successfully linked teleporter <gold>%teleport1% <yellow>with <gold>%teleport2%'
  Removed: '<yellow>Teleporter <gold>%tpname% <yellow>has been removed'
  Unlinked: '<gold>%teleport1% <yellow>has successfully unlinked with <gold>%teleport2%'
  NoDestination: '<red>%tpname% has no destination!'
  ListHeader: '<yellow>---- ====== [ <gold>Your teleporters <yellow>] ====== ----'
  ListNoTeleporters: '<red>You don''t have any teleporters yet'
  SpecifyTeleporter: '<red>Please specify a teleporter!'
  SpecifyMoreTeleporter: '<red>Please specify at least two teleporters!'
  PermissionBlocks: '<red>You don''t have permission to set more teleporters!'
  HelpHeader: '<yellow>---- ====== [ <gold>Teleporters <yellow>] ====== ----'
  HelpAdd: '<gold>/teleporter add <gray>- <yellow>Set teleportation block'
  HelpHelp: '<gold>/teleporter help <gray>- <yellow>This help page'
  HelpLink: '<gold>/teleporter link <gray>[tpblock1] [tpblock2] <yellow>- Link two teleportation blocks together'
  HelpList: '<gold>/teleporter list <gray>- <yellow>Get a list of all your teleporters'
  HelpRemove: '<gold>/teleporter remove <gray>- <yellow>Remove a teleportation block'
  HelpUnlink: '<gold>/teleporter unlink <gray>[tpblock1] <yellow>- Unlink two teleportation blocks. Only need to specify one.'
MiscellaneousLocale:
  Permission: '<red>Sorry, but you do not have permissions to do that.'
  WorldguardPermission: '<red><bold>Hey! <gray>Sorry, but you can''t use that elevator here.'
  GDPremission: '<red>You do not have accesstrust in this claim.'